/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
<<<<<<< HEAD
import { Route as CorporateEventsRouteImport } from './routes/corporate-events'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as EventsRouteImport } from './routes/events'
import { Route as PrivatePartiesRouteImport } from './routes/private-parties'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as WeddingDjRouteImport } from './routes/wedding-dj'
=======
import { Route as EventsRouteImport } from './routes/events'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ServicesRouteImport } from './routes/services'
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const CorporateEventsRoute = CorporateEventsRouteImport.update({
  id: '/corporate-events',
  path: '/corporate-events',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const PrivatePartiesRoute = PrivatePartiesRouteImport.update({
  id: '/private-parties',
  path: '/private-parties',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingDjRoute = WeddingDjRouteImport.update({
  id: '/wedding-dj',
  path: '/wedding-dj',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
<<<<<<< HEAD
  '/corporate-events': typeof CorporateEventsRoute
  '/equipment': typeof EquipmentRoute
  '/events': typeof EventsRoute
  '/private-parties': typeof PrivatePartiesRoute
  '/rates': typeof RatesRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/wedding-dj': typeof WeddingDjRoute
=======
  '/events': typeof EventsRoute
  '/rates': typeof RatesRoute
  '/services': typeof ServicesRoute
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
<<<<<<< HEAD
  '/corporate-events': typeof CorporateEventsRoute
  '/equipment': typeof EquipmentRoute
  '/events': typeof EventsRoute
  '/private-parties': typeof PrivatePartiesRoute
  '/rates': typeof RatesRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/wedding-dj': typeof WeddingDjRoute
=======
  '/events': typeof EventsRoute
  '/rates': typeof RatesRoute
  '/services': typeof ServicesRoute
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
<<<<<<< HEAD
  '/corporate-events': typeof CorporateEventsRoute
  '/equipment': typeof EquipmentRoute
  '/events': typeof EventsRoute
  '/private-parties': typeof PrivatePartiesRoute
  '/rates': typeof RatesRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/wedding-dj': typeof WeddingDjRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate-events'
    | '/equipment'
    | '/events'
    | '/private-parties'
    | '/rates'
    | '/services'
    | '/testimonials'
    | '/wedding-dj'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate-events'
    | '/equipment'
    | '/events'
    | '/private-parties'
    | '/rates'
    | '/services'
    | '/testimonials'
    | '/wedding-dj'
=======
  '/events': typeof EventsRoute
  '/rates': typeof RatesRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/events' | '/rates' | '/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/events' | '/rates' | '/services'
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
<<<<<<< HEAD
    | '/corporate-events'
    | '/equipment'
    | '/events'
    | '/private-parties'
    | '/rates'
    | '/services'
    | '/testimonials'
    | '/wedding-dj'
=======
    | '/events'
    | '/rates'
    | '/services'
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
<<<<<<< HEAD
  CorporateEventsRoute: typeof CorporateEventsRoute
  EquipmentRoute: typeof EquipmentRoute
  EventsRoute: typeof EventsRoute
  PrivatePartiesRoute: typeof PrivatePartiesRoute
  RatesRoute: typeof RatesRoute
  ServicesRoute: typeof ServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WeddingDjRoute: typeof WeddingDjRoute
=======
  EventsRoute: typeof EventsRoute
  RatesRoute: typeof RatesRoute
  ServicesRoute: typeof ServicesRoute
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/corporate-events': {
      id: '/corporate-events'
      path: '/corporate-events'
      fullPath: '/corporate-events'
      preLoaderRoute: typeof CorporateEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/private-parties': {
      id: '/private-parties'
      path: '/private-parties'
      fullPath: '/private-parties'
      preLoaderRoute: typeof PrivatePartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-dj': {
      id: '/wedding-dj'
      path: '/wedding-dj'
      fullPath: '/wedding-dj'
      preLoaderRoute: typeof WeddingDjRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
<<<<<<< HEAD
  CorporateEventsRoute: CorporateEventsRoute,
  EquipmentRoute: EquipmentRoute,
  EventsRoute: EventsRoute,
  PrivatePartiesRoute: PrivatePartiesRoute,
  RatesRoute: RatesRoute,
  ServicesRoute: ServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
  WeddingDjRoute: WeddingDjRoute,
=======
  EventsRoute: EventsRoute,
  RatesRoute: RatesRoute,
  ServicesRoute: ServicesRoute,
>>>>>>> 8ebfb26db11026ca86d131d4936007fb0f391029
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
